#ifndef ERRORS_ISOTP_ERROR_H
#define ERRORS_ISOTP_ERROR_H
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum ISOTPERROR{
    ISOTP_N_CR_TIMEOUT,
    ISOTP_INVALID_CONSECUTIVE_FRAME,
    ISOTP_SEQUENCE_NUMBER_MISMATCH,
    ISOTP_INVALID_FIRST_FRAME_LENGTH,
    ISOTP_INVALID_FRAME_TYPE,
    ISOTP_N_BS_TIMEOUT,
    ISOTP_INVALID_FLOW_CONTROL_FRAME,
    ISOTP_FLOW_CONTROL_FRAME_MAX_EXCEEDED,
    ISOTP_FLOW_CONTROL_OVERFLOW_ABORT,
    ISOTP_INVALID_FLOW_CONTROL_STATUS,
}ISOTPERROR;

void IsoTpError(ISOTPERROR error);

#ifdef __cplusplus
}
#endif

#endif /* ERRORS_ISOTP_ERROR_H */
